JS3 Week2 homework added
KavyaReddy732/hyf-homework pull request #14
Opened 2020-09-27 00:50 UTC by KavyaReddy732

2020-09-30 19:33 UTC, bashirmja requested changes
Great job, but I made a few comments, and please refactor your code and remove all child selectors as I mentioned in the comments.

2020-09-30 19:33 UTC, bashirmja commented on javascript/javascript3/week2/index.js
> +async function movie() {
Functions should name with a verb and a name. 
for example: getData(), SetDate() and ets

2020-09-30 19:33 UTC, bashirmja commented on javascript/javascript3/week2/index.js
> +    const promise = new Promise((resolve,reject) => {
It is hard to find any usage for reject here

2020-09-30 19:33 UTC, bashirmja commented on javascript/javascript3/week2/promise-visual/main.css
> +ul.marks li:nth-child(1) {
It is recommended to use a class selector instead of using nested child selector

2020-09-30 19:33 UTC, bashirmja commented on javascript/javascript3/week2/promise-visual/main.css
> +ul.marks li:nth-child(1) {
Please refactor your code and remove all nested child selector in css and js files

2020-10-03 09:09 UTC, aina21 approved these changes
good job :+1:

2020-10-03 09:09 UTC, aina21 commented on javascript/javascript3/week2/index.js
> +    .map(element => element);
filter result is an array, so I don't think you need a map here.

2020-10-03 09:09 UTC, aina21 commented on javascript/javascript3/week2/index.js
> +    let geoLocation = new Promise((resolve, reject) =>{
you can use const instead of let.

2020-10-03 09:09 UTC, aina21 commented on javascript/javascript3/week2/index.js
> +    let promise = await new Promise((resolve) => {
same here, try to use const until it doesn't let you.

2020-10-08 12:00 UTC, merged